apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-db-init
  namespace: cake-delight
  labels:
    app: notification-db
data:
  init.sql: |
    USE cake_notifications;
    
    CREATE TABLE IF NOT EXISTS notifications (
        id CHAR(36) PRIMARY KEY,
    
        event_id CHAR(36) NOT NULL,
    
        order_id CHAR(36) NOT NULL,
    
        customer_id VARCHAR(80) NOT NULL,
    
        channel VARCHAR(20) NOT NULL,
    
        recipient VARCHAR(200) NOT NULL,
    
        subject VARCHAR(255),
    
        message TEXT NOT NULL,
    
        status VARCHAR(30) NOT NULL,
    
        error_message TEXT,
    
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
        sent_at TIMESTAMP NULL,
    
        UNIQUE KEY unique_event_channel (
            event_id,
            channel
        )
    );
    
    
    CREATE INDEX idx_notifications_customer
    ON notifications(customer_id);
    
    CREATE INDEX idx_notifications_order
    ON notifications(order_id);